### ISSUE TITLE
RT Pipeline: Load structured data about realtime data into the warehouse

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#1002]
This issue aims to track progress towards transforming the raw downloaded RT protobuf files into a format that can be used in BigQuery

- [x] #356 
- [x] #840 (closed in favor of #1011)
- [x] #1011 (tracking trip updates and service alerts)
- [x] #1051
- [x] #1104 (added by @lauriemerrell)

**Comment by lauriemerrell** [comment]
@evansiroky - Do we want to close this / change this out to reflect the progress on #1011 ? cc @atvaccaro 

1011 replaces #840 referenced in the checklist here

**Comment by evansiroky** [comment]
As of today, we got confirmation from @edasmalchi that the JSON in BigQuery is sufficient for analysis with of vehicle positions. So, this is good to be marked as complete!

#1058 should be done as part of a later effort.

**Comment by lauriemerrell** [comment]
Reopening just until #1104 is done.
