### ISSUE TITLE
RT Pipeline: First pass at creating a GTFS-RT validation pipeline

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#1009]
This is a placeholder issue to track overall progress on building out a GTFS-RT validation pipeline. This can be considered complete when a reliable metabase query exists that assessors can use to tell agencies they assess the frequency with which various GTFS-RT errors occur in a transit agency's GTFS-RT feeds.

MVP:
- [x] https://github.com/cal-itp/gtfs-rt-validator-api/pull/3
- [x] https://github.com/cal-itp/data-infra/pull/757
- [x] https://github.com/cal-itp/gtfs-rt-validator-api/pull/4
- [x] https://github.com/cal-itp/data-infra/issues/787 (to be resolved by https://github.com/cal-itp/data-infra/pull/902?)

Later:
- [x] ~Add a metabase database for GTFS-RT data~ we should be able to use the existing Metabase connection
- [x] https://github.com/cal-itp/data-infra/issues/786
- [x] #1204
- [x] https://github.com/cal-itp/data-infra/issues/357
- [x] #1203

Fixes:
- [x] https://github.com/cal-itp/data-infra/issues/1180

**Comment by holly-g** [comment]
MVP + stretch goals have been met 🎉
