### ISSUE TITLE
Research: All GTFS-RT Speedmaps and Tools available for Better Bus Challenge

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-infra#1065]
## Question

How can ongoing RT speed/delay work best support Caltrans districts and other jurisdictions in improving the bus experience, statewide?

## Metrics

- [ ] Speedmaps and other metrics ran for each operator with available RT data
- [ ] Results segmented by district, reproducible, and accessible alongside other ongoing analysis work ([989](https://github.com/cal-itp/data-infra/issues/989), etc)
- [ ] Instructions/documentation drafted
- [ ] Instructions/documentation reviewed and complete

## Data sources

* GTFS-RT vehicle positions (existing raw table in warehouse)
* GTFS Schedule data (in warehouse)

## (Data Servicess Team to Copy and Fill Out Below)

The QuVR MD template below will be filled out by a member of the data services team.
This allows us to describe the request, in a way that is easy to hand-off for analysis.
After the research phase, we will sync with the asker to figure out if the metric and dashboard pieces are needed.

Before starting research:

* **Question**: Question written as a single sentence.
* **View**: E.g. `views.gtfs_schedule_fact_daily_feed_files`.
* **Research**:
  - How should the results be presented?
  - When are they needed by?

After reviewing research with the asker:

* **Metric**: what specific calculations are needed?
* **Dashboard**: where should we put the result?

**Comment by atvaccaro** [comment]
@edasmalchi FYI marking this as "in progress" in ZenHub but I think we probably need to consider separate project management for data infra vs analyses. Otherwise our categories aren't going to work well unfortunately.

**Comment by edasmalchi** [comment]
@atvaccaro sounds good... but what's ZenHub anyway?
