### ISSUE TITLE
Create Catastrophic GTFS Errors Dashboard

### ISSUE THREAD

**Issue by e-lo** [cal-itp/data-infra#1074]
**Is your feature request related to a problem? Please describe.**
As a person maintaining the California Transit Database, I'd like to be notified when a feed fails to download and track its resolution.

**Describe the solution you'd like**

A few options:
1. Add Transit Database Maintenance Team (right now really just me) to the email list of feed download failures
2. Generate an issue type  (with template for agency.yml update) using the GH API and assign it to Transit Database Maintenance Team (me for now) so we can track its resolution
3. Do 2, but w/a GH repo solely for tracking GTFS Dataset errors and generating issues which can be publicly viewable-interact-able.

**Describe alternatives you've considered**
Learning about it on slack a few weeks later ;-) 

## @evansiroky update

From some internal conversation, I think we'll try to resolve this by creating a metabase dashboard that sends off an email each morning with the following questions:

- [x] Which organizations don't have a feed to begin with?
- [x] #1205
- [x] Which feeds have serious syntax errors?
- [x] #1206
- [x] Which feeds have expired or are about to expire?

**Comment by holly-g** [comment]
I was reminded by Laurie today that we can setup Slack subscriptions in Metabase, in case helpful for tracking and if you'd prefer not to clutter up your inbox!
<img width="1483" alt="Screen Shot 2022-02-23 at 5 24 16 PM" src="https://user-images.githubusercontent.com/26711083/155439584-11a29ab4-f4ed-44b7-9001-de13c9718b78.png">

**Comment by Nkdiaz** [comment]
Worth mentioning that several of the questions have internal filters for date. For [Metabase Question: Which GTFS Schedule feeds have zero service hours in the future?](https://github.com/cal-itp/data-infra/issues/1206) I added a dashboard wide filter for date. Assuming I have the go ahead, I would recommend to remove the internal filters and apply the dashboard wide filter to the existing questions for consistency/best practice

**Comment by evansiroky** [comment]
All items asked for within this epic have been completed. Well done everyone!
