### ISSUE TITLE
User Story: Process to flag and/or delete obsolete tables

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1355]
## User stories

As a data scientist, I want to be able to delete unused tables in the BigQuery warehouse so that the production datasets only contain current, active tables (to reduce clutter and make it clear which tables are usable.)

Some considerations that must be decided:

- [ ] "Soft-delete": We likely want to make a holding dataset (for example `deprecated`) and some naming convention for how to move tables out of their prod locations
- [ ] "Hard delete": Do we want to set an expiration date on the soft-delete location so that unused tables are ultimately hard-deleted?

### Acceptance Criteria

To resolve this ticket we should,

- [ ] Define a process that can be used to remove deprecated tables from production BigQuery datasets
- [ ] Record that process in a central location (likely docs.calitp.org)
- [ ] Ensure that the process allows us to resolve #1026 (which can then be resolved one by one outside this ticket based on the new process)

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified

**Comment by atvaccaro** [comment]
Another consideration: what should we do about disabled/deleted models whose materialized artifacts may still be available in metabase or jupyter? We should probably flag them at minimum in some manner, such as Metabase description strings.

**Comment by lauriemerrell** [comment]
Considerations I am aware of now (partial restate of @atvaccaro's point above):

* Models can be deleted in dbt project but persist in BQ warehouse. 
* Metabase can access tables in BQ that are not in dbt (Metabase sync is at the dataset/schema level, ex `mart_gtfs`). 
* JupyterHub can access tables in BQ that are not in dbt.


I think the goal here is to remove deprecated models from places that are accessible to Metabase / JupyterHub, not just to document. Perhaps there is a 2-tiered thing where we first document and then deprecate, but I think the goal is that non-maintained tables are not available in consumer-facing tools.

**Comment by SorenSpicknall** [comment]
Here's a suggestion for basic process:

**Phase 1**
Identify deletion candidates and group into two categories - in active use, and not in active use. We can define an arbitrary activity cutoff to make this distinction, like two weeks since the last query.

**Phase 2**
For models/tables that _aren't_ in active use, give a one-week warning about upcoming deletion in relevant Cal-ITP venues (like the #data Slack channel and the #data-warehouse-devs Slack channel). After that, soft-delete (delete dbt jobs, and label the resulting tables as deprecated) for one week. If entire datasets (schemas) are deprecated, _immediately_ remove them from Metabase and other downstream tools that fetch from an explicit list of datasets. At the end of the two weeks, hard-delete the tables.

For models/tables that are still in active use, give a two-week warning about upcoming deletion in relevant Cal-ITP venues and suggest alternatives if there's a drop-in replacement. During the latter half of the second week, determine whether models/tables are still in active use and do targeted outreach to any heavy users. After that, soft-delete (turn off models and relabel tables) for two weeks using the same whole-dataset removal strategy as above for Metabase. At the end of the four weeks, determine whether there are any stale tables still in active use. Immediately hard delete those that are out of active use, and determine next steps for the remaining tables on a case-by-case basis.

**Considerations**
As others have mentioned, it may be desirable to cold-store tables that we delete somewhere for a longer period. Perhaps six-month retention in GCS?

I left the final steps for tables that remain in active use ambiguous, because if we still see query activity after a four-week warning period, it would likely indicate a user who doesn't know what they're depending on, isn't looped into the deletion conversation, or doesn't have enough available time/labor to implement changes. We don't want to break anything as a result of those situations, so the remainders after four weeks should likely be individually managed.

**Comment by lauriemerrell** [comment]
Thanks @SorenSpicknall, at a high level I think that sounds good. Just a couple observations: 
* To clarify, I think the primary use case for this process right now is tables that are *already* deleted in dbt (or that were never migrated to dbt at all), so I think that the big concern right now is that there are extant tables in BigQuery that are not being refreshed. So I think there are kind of two paths to cover: What steps does someone take when deprecating an existing model in dbt (defining a future workflow) and what steps do we take to deprecate things that already don't exist in dbt (covering the state that we're in right now). I think your proposal can work but since you mentioned deleting the dbt model as one of the steps, I just wanted to clarify what I think the current state is (already deleted dbt models).
* I am not sure if you were putting this out there with the intent to validate and then define the details, so sorry if you were planning to follow up on this, but my big question has been: what specifically does soft deletion look like on the BQ side, i.e, how exactly do we mark something as deprecated? If it's a docs-only change, that is probably invisible to most users (so we're basically relying on Slack exclusively for the notification) or do we physically copy the table and prefix it with deprecated, in which case we will immediately break people's workflows? That might be fine for the not-in-active-use case but I just wanted to clarify. 
* I think that cold storage is unnecessary for things that were ever in dbt because worst case we can resurrect the SQL from the git history and just re-run it. That is less obvious for me for tables that were never in dbt at all, but presumably they are so far out of use that a hard delete is ok (and even there we can generally recover the SQL that created them, I think.)

**Comment by SorenSpicknall** [comment]
> I think there are kind of two paths to cover: What steps does someone take when deprecating an existing model in dbt (defining a future workflow) and what steps do we take to deprecate things that already don't exist in dbt (covering the state that we're in right now). I think your proposal can work but since you mentioned deleting the dbt model as one of the steps, I just wanted to clarify what I think the current state is (already deleted dbt models).

In the case where models are already deleted, I think we'd just start at the next step (soft deletion of resulting tables if we're still seeing query activity on the tables, and hard deletion if not).

> my big question has been: what specifically does soft deletion look like on the BQ side, i.e, how exactly do we mark something as deprecated?

I'd like to go the route of renaming the tables or datasets impacted by the deprecation. In this case, I believe that breaking existing workflows is actually desirable, since it necessitates action. We can announce where things have been moved for the X weeks that they're deprecated but not yet deleted, so that people can make code changes to point at the old table structures if needed while moving toward relying on newer tables. Would that be acceptable?

> I think that cold storage is unnecessary for things that were ever in dbt because worst case we can resurrect the SQL from the git history and just re-run it. That is less obvious for me for tables that were never in dbt at all, but presumably they are so far out of use that a hard delete is ok (and even there we can generally recover the SQL that created them, I think.)

I'll defer to you, Andrew, Charlie, and Jameelah on this one. If you think there's no use for cold storage in this context, I trust you.
