### ISSUE TITLE
GTFS Schedule Pipeline: `gtfs_loader` updates

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#1532]
Epic containing tasks related to item [#4 gtfs_loader DAG updates from the GTFS Schedule Pipeline Proposal - May 2022 project](https://docs.google.com/document/d/1tPPpZMgPfRNviarF2BrSrwZYtSGnPzGcT75erHo-UZ0/edit#heading=h.62fqokbddnhj).

TODO before backfill / unpausing new unzipper & validation DAGs: 
- [ ] Decide on processing intervals for downloader vs. loader (ex. does downloader run at midnight UTC or 2300 UTC / is unzipper processing "prior" day or "same" day)
- [ ] Make sure that all `PodOperators` & Airflow `requirements.txt` are using the same, latest version of `calitp-py` 
- [ ] Make sure that all results files are gzipped
