### ISSUE TITLE
Date/time processing & warehouse audit 

### ISSUE THREAD

**Issue by lauriemerrell** [cal-itp/data-infra#2325]
As a result of #2306 and #2323, we want someone to spend some time reviewing the interaction of processing times throughout our GTFS & Airtable data ingest and check for anything that seems risky. 

AC:

- [ ]  For our core concepts (RT, RT validations, GTFS schedule, GTFS schedule validations, Airtable GTFS datasets), audit the following (UTC & Pacific Time):
   - [ ]  When raw data is scraped 
   - [ ]  When that raw data is picked up for processing in Airflow
   - [ ]  When that raw data becomes available in the mart schemas in the warehouse (dependency between raw data processing and dbt run job)
   - [ ]  Any key dependencies with other raw data, and what vintage of that data is being used
- [ ]  Identify any other core "date" concepts (ex. `service_date` within GTFS, `activity_date` just defined in #2275, perhaps contract dates?) and do at least a quick review of where they intersect with processing time
- [ ] Document high-level findings from the above, perhaps here: https://dbt-docs.calitp.org/#!/overview/calitp_warehouse; specifically:
   - [ ] Naming conventions for different "types" of dates (ex. dimension validity dates vs. fact event dates)
   - [ ] How time zones should be interpreted

**Comment by lauriemerrell** [comment]
See this [Slack thread](https://cal-itp.slack.com/archives/C01FNDG1ZPA/p1679614346576869) for discussion of a related issue. As of right now (9am Pacific on Friday, March 24) the most recent data in the warehouse is from 8pm Pacific on Wednesday, March 22.

**Comment by lauriemerrell** [comment]
Another example: Airtable data for Santa Ynez Schedule updated on Tuesday Pacific. As of Thursday 6pm Central, data downloaded from the new URL is still not available in the warehouse.

**Comment by lauriemerrell** [comment]
I think that the concerns here were addressed by:

* #2460 
* #2457 
* #2489
