### ISSUE TITLE
User Story: Onboarding documentation for analytics users

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-infra#689]
### Summary

1. **As a** new analyst or non-analyst team member looking to use our analytics resources
2. **I want**  an early document
3. **So that** I can see early on the scope of the tools our team uses, and I can ask to get added to those that I'm not already

### Acceptance Criteria

1. If I'm going through the docs, I can find onboarding early on
2. After reading the doc I know which tools are used for which analytics function
3. After reading the doc I know where to go to find out more about the tools
4. If I'm lost I can use the page's concise descriptions to reorient
5. If I'm a non-analyst team member I can use the page to see which tools are available to me
6. If I'm a non-analyst team member I can find who to contact for access

### Notes
* Just need to make sure that we're capturing the multi-use of this section, for both new analysts and non-analyst team members 
* This section should be easy to find, first encounter, early in the docs

Tasks to complete

- [x] Collapse into one page
- [x] Add descriptions of tools
- [x] Remove 'Organizations' and 'Teams' from below GH section
- [x] Write intro content
- [x] Add how to get added content
- [x] Make sure all resources are captured in the list
- [x] Link out to the more detailed sections beneath
- [x] Research how to format high-level information blocks 
- [x] Implement high-level information blocks 

### Tester [Stakeholder]

1.

# Sprint Ready Checklist
1. - [x] Acceptance criteria defined
2. - [x] Team understands acceptance criteria
3. - [x] Team has defined solution / steps to satisfy acceptance criteria
4. - [x] Acceptance criteria is verifiable / testable
5. - [x] External / 3rd Party dependencies identified

**Comment by charlie-costanzo** [comment]
cc @holly-g another user story out in the wild! tagging you in this for review/feedback

**Comment by machow** [comment]
From pairing w/ Charlie--let's consider this as ready to implement, so he can keep moving, while we write out epics for the rest of the docs.

**Comment by charlie-costanzo** [comment]
Tasks to complete

- [ ] Collapse into one page
- [ ] Add descriptions of tools
- [ ] Remove 'Organizations' and 'Teams' from below GH section
- [ ] Write intro content
- [ ] Add how to get added content
- [ ] Link out to the more detailed sections beneath
