### ISSUE TITLE
Load Airtable data into warehouse

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#774]
There is currently a bunch of useful data in Airtable that could be even more useful if imported into the warehouse such that analysts could play with the data and such that metabase could bring in the data.

Issues (in order of priority):

- [x] Create proof-of-concept Airtable operator and DAG sandbox (resolved with #518)
- [x] #973
- [ ] Transit Data Assessments
- [ ] #1159
- [ ] Data Maturity Framework

After completing this, the transitstacks DAGs should maybe be retired.

**Comment by evansiroky** [comment]
This was completed a while ago.
