### ISSUE TITLE
handoff: calitp extraction packages and calitp-py walkthrough

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#850]
## Resources

* https://github.com/cal-itp/gtfs-rt-validator-api
* https://github.com/cal-itp/gtfs-validator-api
* https://github.com/cal-itp/calitp-py

## Goals

- [x] : can deploy new versions
- [x] : can deploy / check new docker image releases
- [x] : can go through local debugging / testing workflow
- [x] : familiar with where they are used (e.g. KubernetesPodOperator tasks, [example](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_downloader/validate_gcs_bucket.yml))
- [ ] : update docs prior to meeting to state key problems solved
- [ ] : update docs after based on feedback

## TODO

- [ ] : screencast deploying calitp py

## Relevant Issues

* #828 
* #759 
* #758

**Comment by machow** [comment]
## Which needs the most work?

calitp-py is the workhorse of the warehouse, since it connects analysts to the pipeline. It definitely seems like the one to add a lot of QoL improvements to

**Comment by holly-g** [comment]
See #1072 (spun out to wrap up the docs piece)
