### ISSUE TITLE
Address GTFS RT extractor service issues

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#896]
@lottspot this is just to organize gtfs rt extractor issues into one place. We're onboarding @chriscauley, who can help the gtfs rt extractor. Do you mind syncing with him to walkthrough the service? (he is `@cauley` on the jarvus slack).

- [x] https://github.com/cal-itp/data-infra/issues/888 
- [x] https://github.com/cal-itp/data-infra/issues/882
- [x] https://github.com/cal-itp/data-infra/issues/868
- [x] https://github.com/cal-itp/data-infra/issues/815

**Comment by holly-g** [comment]
Prioritizing #882

**Comment by evansiroky** [comment]
I just updated the description to have a checklist of issues.
