### ISSUE TITLE
Contact known agencies missing feed_info.txt

### ISSUE THREAD

**Issue by holly-g** [cal-itp/data-infra#904]
**Problem** 
Agencies without the required `feed_info.txt` are unable to be included in the reports site (they break our report generation). Olivia identified the following agencies with known GTFS schedule feeds who do not have `feed_info.txt` in #800.  

**Agencies**

- [ ]  B-Line
- [ ]  Beach Cities
- [ ] County Connection
- [ ] City of Lompoc Transit
- [ ] Foothill Transit
- [ ] GET Bus
- [ ] Glendale beeline
- [ ] Gold Coast transit
- [ ] Golden Gate Bridge Highway and Transportation District
- [ ] KART (Kings Area Rural Transit)
- [ ] Manteca Transit
- [ ] Menlo Park Shuttles
- [ ] MUNI
- [ ] Omnitrans
- [ ] OCTA
- [ ] Pasadena Transit
- [ ] Samtrans
- [ ] San Luis Obispo Regional Transit Authority
- [ ] Tri-Valley Wheels
- [ ] Yolobus

**Questions**  
- [ ] How do we currently work with agencies to help support their publishing of feeds and [GTFS best practices](https://gtfs.org/best-practices/)?  
- [ ] Can we track this in the CRM? 

**TO-DO**  
- [ ] Move spreadsheet over to CRM ? [@holly-g]
- [ ] Identify Cal-ITP point of contact who will be conducting outreach to agencies
- [ ] Establish contact with agencies to inform them of the missing `feed_info_txt`   
- [ ] Identify point of contact from agency and ask questions to seek to understand the underlying reason it was missing, and any unforeseen issues (tracked in the CRM)
