### ISSUE TITLE
Automate checking of whether agencies' URLs exist on feed aggregator websites

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#924]
## User Story

**As a** transit data assessor, 
**I want to** know if the URLs of a transit agency's GTFS data exist on all of the transit aggregator websites, 
**so that** 
1) I can communicate to transit agencies whether or not they should be doing a better job of telling the world about their data and 
2) tell whether a transit agency is complying with the [GTFS Minimum Guidelines](https://dot.ca.gov/cal-itp/california-minimum-general-transit-feed-specification-gtfs-guidelines) (specifically `Publish all GTFS Schedule and GTFS Realtime datasets to global GTFS aggregators`).

For this user story, the `URLs a transit agency's GTFS data` consist of the following 4 URLs:

1. GTFS Schedule
2. GTFS Realtime Service Alerts
3. GTFS Realtime Trip Updates
4. GTFS Realtime Vehicle Positions

## Acceptance Criteria

**Given** 

1) data found on transit feed aggregator websites (transit.land and transitfeeds.com)
2) data of all of the known URLs for transit data that Cal-ITP maintains

**When** a check is made of each URL that Cal-ITP knows about (as noted in Given statement 2) against all GTFS feed URLs found on all feed aggregator websites
**Then** results should be stored about whether each URL that Cal-ITP knows about exists in each feed aggregator website
**And** (potentially addressable as a part of #574?) results should be displayed within the [GTFS Guidelines Dashboard](https://dashboards.calitp.org/dashboard/26)
**And**  (potentially addressable as a part of #574?) the result should note the reference human-visitabled URL on the applicable feed aggregator website that shows the presence of the URL if it is available.

**Example:**

For the agencies.yml entry `Torrance Transit`:

```yml
torrance-transit-system:
  agency_name: Torrance Transit System
  feeds:
    - gtfs_schedule_url: https://transit.torranceca.gov/home/showdocument?id=16673
      gtfs_rt_vehicle_positions_url: null
      gtfs_rt_service_alerts_url: null
      gtfs_rt_trip_updates_url: null
  itp_id: 339
```

This feed does not exist on transitfeeds.com, but it does on transit.land [here](https://www.transit.land/feeds/f-9q5b-torrancetransit).

Therefore, something like the following table should be shown w/r/t Torrance Transit:

|URL type|URL|In transitfeeds.com?|In transit.land?|
|--|--|--|--|
| gtfs_schedule_url | https://transit.torranceca.gov/home/showdocument?id=16673 | Absent | [Present](https://www.transit.land/feeds/f-9q5b-torrancetransit) |
| gtfs_rt_vehicle_positions_url | null | N/A | N/A |
| gtfs_rt_service_alerts_url | null | N/A | N/A |
| gtfs_rt_trip_updates_url | null | N/A | N/A |

## Sprint Ready Checklist

- [ ]  Acceptance criteria defined
- [ ]  Team understands acceptance criteria
- [ ]  Team has defined solution / steps to satisfy acceptance criteria
- [ ]  Acceptance criteria is verifiable / testable
- [ ] Dependencies identified

**Comment by holly-g** [comment]
cc @chriscauley, another issue for us to tee up and discuss on Monday (1/10)

**Comment by evansiroky** [comment]
Just to clarify, this should be done for all the URLs we have. There should be checks whether all of: static feed URL, trip updates URL, vehicle positions URL and alerts URL.

**Comment by holly-g** [comment]
@evansiroky now that this is happening https://database.mobilitydata.org/, should https://www.transit.land/ be the sole preimary feed aggregator for us to check?

**Comment by evansiroky** [comment]
@holly-g, the new mobility data database is still in the process of being made. So let's keep checking transitfeeds.com until it is officially deprecated.

**Comment by holly-g** [comment]
@atvaccaro, for your awareness, Evan updated the ticket to reflect the new user story/accceptance criteria format 🎉  This provides helpful context/clarity around the scope of this ticket!
