### ISSUE TITLE
Ingest Amplitude events for Benefits metrics in Metabase

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/data-infra#960]
**Is your feature request related to a problem? Please describe.**

Currently, an Amplitude user must log in and manually view and/or export dashboard charts and metrics for Benefits app activity. This is not such a problem now, but we're anticipating more frequent requests from a more diverse audience for this type of information. Having it centrally located with other key Cal-ITP metrics provides for more self-service opportunities and consistent reporting across the program.

**Describe the solution you'd like**

Metabase should have enough information to be able to represent the key metrics related to activity in the Benefits app:

* Total number of eligibility checks
* Number of unique users that checked eligibility
* Total number of enrollments
* Number of unique users that enrolled
* Total number of application page views

Additionally we'd like to be able to segment by:

* Language (English, Spanish)
* Transit Agency (MST, eventually SacRT, perhaps others)

**Describe alternatives you've considered**

We currently have these metrics/charts built out in Amplitude. It doesn't seem feasible to provide accounts for anyone/everyone wishing to view the metrics, nor does it make sense to have folks jumping between various dashboard tools to get a high-level picture of Cal-ITP.

**Additional context**

I can see at least three ways to make this happen (with not much preference other than 1 coming with a $$$ tag):

1. Pay for Amplitude to get access to advanced "Data Destinations" (built in event exports), which includes a [GCS connector](https://help.amplitude.com/hc/en-us/articles/360061685151-Export-Amplitude-data-to-Google-Cloud-Storage). From there, the raw event data could move into the warehouse and then on to Metabase. Likely huge overkill unless Cal-ITP wanted to start using Amplitude across various projects.
2. Use Amplitude's [Export API](https://developers.amplitude.com/docs/export-api) via Airflow or similar, writing code to do something like what the paid Amplitude plans do from Amplitude --> GCS --> Warehouse --> Metabase
3. Use Amplitude's [Dashboard API](https://developers.amplitude.com/docs/dashboard-rest-api) to export the pre-computed metrics, maybe directly into Metabase? I don't know if that even makes sense.

**Comment by holly-g** [comment]
Based on backlog grooming call with Evan, Kegan will be taking a first pass at this. @thekaveman please let us know if you need any support from us!

**Comment by thekaveman** [comment]
In #518 a new *warehouse operator* was introduced to get data from [Airtable](https://www.airtable.com/) in the GCP BigQuery warehouse. This is a bit of python code that takes data from the Airtable API and puts it in a format that the rest of the pipeline can understand. Read more about [Apache Airflow](https://airflow.apache.org/docs/apache-airflow/stable/index.html), [DAGs](https://airflow.apache.org/docs/apache-airflow/stable/concepts/dags.html), and [Operators](https://airflow.apache.org/docs/apache-airflow/stable/concepts/operators.html)

We can follow a similar model here to create a *warehouse operator* for data from Amplitude's API - this will be an implementation of approach 2 above. General outline as follows:

1. [ ] Create a module in [`airflow/plugins/operators`](https://github.com/cal-itp/data-infra/tree/main/airflow/plugins/operators) like `amplitude_to_warehouse.py`; see [`airtable_to_warehouse.py`](https://github.com/cal-itp/data-infra/blob/main/airflow/plugins/operators/airtable_to_warehouse.py) as an example
2. [ ] Create a function in the module like `amplitude_to_df()` to download Amplitude data and return it in a DataFrame. This function should take as parameters all API keys, querystrings, etc. needed to get at the data, perhaps reading from `os.env` if a value is not provided. See the [Amplitude Export API docs](https://developers.amplitude.com/docs/export-api)
3. [ ] Create a class in the module inheriting from `airflow.models.BaseOperator` like `AmplitudeToWarehouseOperator`
4. [ ] In the class `__init__()`, take in any API keys etc. and remember to call `super().__init__(**kwargs)`
5. [ ] In the class implement an `execute(self, context)` method that calls the `amplitude_to_df` function and saves the resulting DataFrame to the warehouse using [`calitp.write_table()`](https://github.com/cal-itp/calitp-py/blob/main/calitp/sql.py#L76)
6. [ ] Import the new operator class in [`airflow/plugins/operators/__init__.py`](https://github.com/cal-itp/data-infra/blob/main/airflow/plugins/operators/__init__.py)
7. [ ] In [`airflow/dags/sandbox`](https://github.com/cal-itp/data-infra/tree/main/airflow/dags/sandbox) create a [`gusty`](https://github.com/chriscardillo/gusty) YAML file defining a DAG like `op_amplitude_to_warehouse.yml`; this DAG is defined in the sandbox environment for testing purposes. See [`op_airtable_to_warehouse.yml`](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/sandbox/op_airtable_to_warehouse.yml) as an example.

See https://github.com/cal-itp/data-infra/blob/main/airflow/README.md for more on running the Airflow pipeline locally.

**Comment by machikoyasuda** [comment]
Updating the general work plan:

0. [ ] @angela-tran: Pull data from Amplitude API to see what the data schema is.
1. [ ]  Come up with the common schema of the table (May need to involve data analysts/operators and get their input, approval).

## Amplitude to Airflow task

1. [ ] Create a module in [`airflow/plugins/operators`](https://github.com/cal-itp/data-infra/tree/main/airflow/plugins/operators) like `amplitude_to_warehouse.py`; see [`airtable_to_warehouse.py`](https://github.com/cal-itp/data-infra/blob/main/airflow/plugins/operators/airtable_to_warehouse.py) as an example
2. [ ] Create a function in the module like `amplitude_to_df()` to download Amplitude data and return it in a DataFrame. This function should take as parameters all API keys, querystrings, etc. needed to get at the data, perhaps reading from `os.env` if a value is not provided. See the [Amplitude Export API docs](https://developers.amplitude.com/docs/export-api)

## Airflow Operator task

_Assume you already have the Amplitude data in the proper format/schema:_

3. [ ] Create a class in the module inheriting from `airflow.models.BaseOperator` like `AmplitudeToWarehouseOperator`
4. [ ] In the class `__init__()`, take in any API keys etc. and remember to call `super().__init__(**kwargs)`
5. [ ] In the class implement an `execute(self, context)` method that calls the `amplitude_to_df` function and saves the resulting DataFrame to the warehouse using [`calitp.write_table()`](https://github.com/cal-itp/calitp-py/blob/main/calitp/sql.py#L76)
6. [ ] Import the new operator class in [`airflow/plugins/operators/__init__.py`](https://github.com/cal-itp/data-infra/blob/main/airflow/plugins/operators/__init__.py)
7. [ ] In [`airflow/dags/sandbox`](https://github.com/cal-itp/data-infra/tree/main/airflow/dags/sandbox) create a [`gusty`](https://github.com/chriscardillo/gusty) YAML file defining a DAG like `op_amplitude_to_warehouse.yml`; this DAG is defined in the sandbox environment for testing purposes. See [`op_airtable_to_warehouse.yml`](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/sandbox/op_airtable_to_warehouse.yml) as an example.

**Comment by thekaveman** [comment]
We also need to think about where this data lands once it gets into _Metabase_

Over in #983 @lauriemerrell indicates that within Metabase, data must live in a single dataset in order to be joined - e.g. if we ever wanted to join Benefits analytics with payments data, that data must all be in the same Metabase dataset.

**Comment by thekaveman** [comment]
Thank you @lauriemerrell!!

I was chatting with @holly-g and I think we're going to schedule some time next week with all of us to talk through some of these items. Looking forward to it.
