### ISSUE TITLE
Ability to segment and analyze GTFS data by "Services"

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#976]
**Is your feature request related to a problem? Please describe.**

In the transit database, we are tracking "Services". Services are public transport services that one or many organizations provide. Sometimes, a GTFS dataset can have multiple services within it. This is obviously possible with regional feeds, but it can also happen where one transit agency has multiple services (for example SacRT rail and SacRT bus are considered two services that are described in one GTFS dataset). It would be great to be able to analyze these subsets of services in our data pipeline such that it would be possible to analyze the GTFS data associated with a service just like it is possible today to analyze the services described in a whole GTFS dataset today.

**Describe the solution you'd like**

Stuff that needs to happen to get this working:

- [ ] #774
- [ ] #775
- [ ] Have ability to filter a GTFS dataset into a service subcomponent
- [ ] Update pipeline to be able to analyze service subcomponent GTFS feeds
- [ ] Have ability to filter a GTFS-RT dataset into a service subcomponent

**Describe alternatives you've considered**

Not doing it at all and just using GTFS datasets like we are today, but we probably should do this.

**Additional context**

This will help us identify any issues occurring with specific parts of transit agencies. Also, the assessment team would then have an easier time assessing service-based questions.
